name: edu-ai-learning-assistant
region: nyc

services:
  # Backend API Service
  - name: backend
    github:
      repo: Musmannazir/Edu-AI
      branch: main
      deploy_on_push: true
    source_dir: backend
    environment_slug: python
    build_command: pip install -r requirements.txt
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
      - key: YOUTUBE_API_KEY
        value: ${YOUTUBE_API_KEY}
        type: SECRET
      - key: DATABASE_URL
        value: sqlite:///./learning_assistant.db
      - key: CORS_ORIGINS
        value: ${frontend.PUBLIC_URL}
    health_check:
      http_path: /docs

  # Frontend Static Site
  - name: frontend
    github:
      repo: Musmannazir/Edu-AI
      branch: main
      deploy_on_push: true
    source_dir: frontend
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
